version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=super_secret_lab_key_2024
    depends_on:
      - db
    volumes:
      - ./app:/app
    
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: lab_root_password_123
      MYSQL_DATABASE: secret_lab
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_password_456
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: 